# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-10-06 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentBookingSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='staffId',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='AppointmentBookingSystem.Staff'),
        ),
    ]
