# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-10-05 04:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentBookingSystem', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
    ]
