# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-10-06 05:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentBookingSystem', '0002_auto_20191006_0545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='staffId',
        ),
    ]
