# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-10-05 05:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentBookingSystem', '0003_auto_20191005_0437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='serviceId',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='staffId',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='userId',
        ),
        migrations.DeleteModel(
            name='Bookings',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
