# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-10-05 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentBookingSystem', '0005_auto_20191005_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
